### ISSUE TITLE
Akamai EdgeGrid authentication 

### ISSUE THREAD

**Issue by githuboleh** [IBM/IBM-QRadar-Universal-Cloud-REST-API#92] opened 2022-02-12 02:05 UTC
Hello

Has anyone got Akamai EdgeGrid authentication working for uDSM cloud rest api? If anyone has example, please share. Thank you

**Comment by githuboleh** [comment] 2022-02-14 15:12
I am getting com/akamai/edgegrid/singer/clientcredential error

I have used <AkamaiEdgeGridAthentication but looks like I could be missing something. Any help will be appreciated. Thank you

**Comment by phogan2001** [comment] 2022-03-21 17:53
Interested to see if you make any progress, part of the issue is with EdgeGrid and that it calculates authorization header for each request https://developer.akamai.com/legacy/introduction/Client_Auth.html  and the worflow.xml files are just static , if you make any progress please share

**Comment by ChrisCollinsIBM** [comment] 2022-07-06 17:16
This looks like it was released in early 2021

Anything after these should be good:

PROTOCOL-UniversalCloudRESTAPI-7.3-20210225193705.noarch.rpm
PROTOCOL-UniversalCloudRESTAPI-7.4-20210226025732.noarch.rpm

Please let us know if it's still an issue!

**Closed by ChrisCollinsIBM** 2022-07-06 17:16 UTC
